/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
*/
#include <iostream>
using namespace std;

int main()
{
    int m = 1, n = 2, sum = 2, ans;
    while (true)
    {
        ans = m + n;
        m = n;
        n = ans;
        if (ans >= 4000000)
            break;
        if (ans % 2 == 0)
            sum +=  ans;
    }
    cout << sum << endl;
    return 0;
}
